### ISSUE TITLE
how to use clickhouse sql parser

### ISSUE THREAD

**Issue by duokaluo88** [DLuPan/DorisParser#1]
大佬，clickhouse的解析器是否完成，有没有使用例子

**Comment by DLuPan** [comment]
ck解析器目前生成的是antlr4模式的ast树，简单使用可以通过visitor+listener实现，我这里因为业务目前仅需要部分表及字段信息所以demo只提供了这部分内容，后续等ast-common弄好了，会将ck的默认ast转化为优化后的ast-common模型会更好用一点。
parser-clickhouse/src/test/java/com/lfsenior/sql/parser/clickhouse/ClickhouseSqlParserTest.java

**Comment by duokaluo88** [comment]
3q
