### ISSUE TITLE
cup-maven-plugin 插件问题

### ISSUE THREAD

**Issue by hqisog** [DLuPan/DorisParser#2]
<plugin>
                <groupId>net.sourceforge.czt.dev</groupId>
                <artifactId>cup-maven-plugin</artifactId>
                <version>1.6-cdh</version>
这个插件，我这边下载不下来，找不到

**Comment by DLuPan** [comment]
`
 
  <repository>
      <id>cloudera-public</id>
      <url>https://repository.cloudera.com/artifactory/public/</url>
  </repository>
`
插件是这个仓库里的，检查下maven配置是不是有问题

**Comment by hqisog** [comment]
亲，我已经收到了你的来件。

**Comment by hqisog** [comment]
能发下，你的maven配置吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [DLuPan/DorisParser] cup-maven-plugin 插件问题 (Issue #2)




            cloudera-public       https://repository.cloudera.com/artifactory/public/    插件是这个仓库里的，检查下maven配置是不是有问题 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DLuPan** [comment]
你再maven配置里加一个profile应该就可以了
```xml

  <profiles>
	<profile>
		<id>general-env</id>

		<repositories>
			<repository>
				<id>central</id>
				<name>central maven repo https</name>
				<url>https://repo.maven.apache.org/maven2</url>
			</repository>
			<!-- for java-cup -->
			<repository>
				<id>cloudera-public</id>
				<url>https://repository.cloudera.com/artifactory/public/</url>
			</repository>
			<!-- for bdb je -->
			<repository>
				<id>oracleReleases</id>
				<url>http://download.oracle.com/maven</url>
			</repository>
		</repositories>

		<pluginRepositories>
			<pluginRepository>
				<id>spring-plugins</id>
				<url>https://repo.spring.io/plugins-release/</url>
			</pluginRepository>
			<!-- for cup-maven-plugin -->
			<pluginRepository>
				<id>cloudera-public</id>
				<url>https://repository.cloudera.com/artifactory/public/</url>
			</pluginRepository>
		</pluginRepositories>
	</profile>

  </profiles>

  <activeProfiles>
	<activeProfile>general-env</activeProfile>
  </activeProfiles> 


```

**Comment by hqisog** [comment]
我试试

**Comment by hqisog** [comment]
亲，我已经收到了你的来件。
