### ISSUE TITLE
Doris STRING 类型问题

### ISSUE THREAD

**Issue by tteec** [DLuPan/DorisParser#3]
可以新增对Doris STRING 类型的支持吗，我自己魔改了一下，勉强能用，但是改得不够全面，希望能支持一下

**Comment by DLuPan** [comment]
解析是支持String的，doris将String作为一种特殊的varchar来处理了varchar(*)

**Comment by DLuPan** [comment]
我刚看了doris的源码，他新版本将String作为独立的数据类型来处理了，我周末加进去

**Comment by tteec** [comment]
> 我刚doris的源码，他的新版本将String作为独立的数据类型来处理了，我加了周末

好的 谢谢

**Comment by DLuPan** [comment]
![image](https://user-images.githubusercontent.com/57487213/153556403-374c1e1d-0433-44c7-9508-557d793d9daa.png)
代码已上传 #4
